apply plugin: 'com.android.application'

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    //resourcePrefix "${project.name}_"//资源命名规范暂不约束

    defaultConfig {
        namespace 'com.suheng.structure'
        applicationId "com.suheng.structure"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode rootProject.ext.versionCode
        versionName rootProject.ext.versionName

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            storeFile file('../zhipu-keystore.jks')
            storePassword 'Zhipu@520'
            keyAlias = 'modules_apply'
            keyPassword 'Zhipu@520_'
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.release
            //buildConfigField "boolean", "MODULE1_IS_LIBRARY", "${isModule1Library}"
        }

        release {
            signingConfig signingConfigs.release
            //buildConfigField "boolean", "MODULE1_IS_LIBRARY", "${isModule1Library}"

            minifyEnabled true //代码混淆
            shrinkResources true //资源压缩
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'//,
                    //'../module1/proguard-rules.pro', '../module2/proguard-rules.pro'//合并混淆文件
        }
    }

    applicationVariants.all {
        variant ->
            variant.outputs.all {
                outputFileName = rootProject.name + versionName + "_" + getDate() + ".apk"
            }
    }

    lintOptions {
        disable 'GoogleAppIndexingWarning'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation "androidx.appcompat:appcompat:$rootProject.appcompatVersion"
    testImplementation "junit:junit:$rootProject.junitVersion"
    androidTestImplementation "androidx.test:runner:$rootProject.runnerVersion"
    androidTestImplementation "androidx.test.espresso:espresso-core:$rootProject.espressoCoreVersion"

    implementation project(path: ':common')
    /*if (isModule1Library.toBoolean()) {
        implementation project(path: ':module1')
    }
    if (isModule2Library.toBoolean()) {
        implementation project(path: ':module2')
    }
    if (isModule3Library.toBoolean()) {
        implementation project(path: ':module3')
    }
    if (bluetoothIsLibrary.toBoolean()) {
        implementation project(path: ':bluetooth')
    }*/
}

import java.text.SimpleDateFormat

static String getDate() {
    return new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date())
}

task tk1 {
    println(project.getProperties().get("uploads.releaseVersion"))

    if (project.getProperties().get("uploads.releaseVersion") == "true") {
        println("widgets")
    } else {
        println("widgets-temp")
    }
}